### ISSUE TITLE
Not working: "##[error]Not Found"

### ISSUE THREAD

**Issue by zoispag** [homoluctus/slatify#71]
Hi, since July 24, this action fails, with no good error message.
Any idea?

```yml
    - name: Slack notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '*Validate client configuration*'
        channel: '#testing'
        mention: 'here'
        mention_if: 'failure'
        url: ${{ secrets.SLACK_WEBHOOK }}
        commit: true
        token: ${{ secrets.OAUTH_TOKEN }}
```

![image](https://user-images.githubusercontent.com/21138205/88910527-e50ed480-d25c-11ea-86b8-fbeafaffd438.png)
